CREATE DATABASE IF NOT EXISTS website;
USE website;

CREATE TABLE IF NOT EXISTS `user` (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(256) NOT NULL,
    `password` VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS `changelog` (
	user_id INT NOT NULL,
	`timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	W_ID INT NOT NULL,
	PRIMARY KEY(user_id, `timestamp`, W_ID),
	FOREIGN KEY (user_id) REFERENCES user(id)
);
